[package]
name = "study-groups"
version = "0.1.0"
edition = "2021"

[dependencies]
grokking_algos = { version = "0.1.0", path = "grokking_algos" }
lingua_rustica = { version = "0.1.0", path = "lingua_rustica" }
