[package]
name = "grokking_algos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_structures = { version = "0.1.0", path = "data_structures" }
rand = "0.8.5"
